/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../packages/button/index.js';

const components = [
    Button
];

const install = function(Vue, opts = {}) {
    components.forEach(component => {
        if (component.name) {
            Vue.component(component.name, component);
        }
    });

    Vue.prototype.$opts = {
        size: opts.size || ''
    };
};

/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
    install(window.Vue);
}

export default {
    version: '1.0.0',
    install,
    Button
};
